### ISSUE TITLE
Add demo for Junit 5 to check exception absence/presence

### ISSUE THREAD

**Issue by olibre** [CodeFX-org/demo-junit-5#1]
Please add some Junit 5 demo to check exceptions:

* [`assertAll​()`](https://junit.org/junit5/docs/current/api/org/junit/jupiter/api/Assertions.html#assertAll(java.lang.String,java.util.Collection))  
    *Asserts* that *all* supplied `executables` do not throw exceptions.

* [`assertDoesNotThrow​()`](https://junit.org/junit5/docs/current/api/org/junit/jupiter/api/Assertions.html#assertDoesNotThrow(org.junit.jupiter.api.function.Executable))  
    *Asserts* that execution of the supplied `executable`/`supplier` *does not throw* any kind of [exception](https://docs.oracle.com/javase/8/docs/api/java/lang/Throwable.html?is-external=true).

* [`assertThrows​()`](https://junit.org/junit5/docs/current/api/org/junit/jupiter/api/Assertions.html#assertThrows(java.lang.Class,org.junit.jupiter.api.function.Executable))  
    *Asserts* that execution of the supplied `executable` *throws* an exception of the `expectedType` and returns the [exception](https://docs.oracle.com/javase/8/docs/api/java/lang/Throwable.html?is-external=true).

See also : https://stackoverflow.com/a/51768474/938111

**Comment by nicolaiparlog** [comment]
It's easy to say that eight months after the fact (so sorry!), but have a look at [`AssertTest`](https://github.com/CodeFX-org/demo-junit-5/blob/master/src/test/java/org/codefx/demo/junit5/basics/AssertTest.java) - it contains most of what you're asking. Not, `assertDoesNotThrow`, though, because I find it weird.
